version: '3'

services:
  homebox:
    image: danielrosehill/homebox:fuzzy-search
    container_name: homebox
    ports:
      - "7745:7745"
    volumes:
      - homebox-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O", "-", "http://localhost:7745/api/v1/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Uncomment this section if you want automatic updates
  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 86400 --cleanup --label-enable homebox
  #   restart: unless-stopped

volumes:
  homebox-data:
    # If you want to use a specific directory on your host instead of a Docker volume
    # uncomment and modify the following lines:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /path/on/host/to/data
