name: Build and Push Fuzzy Search Docker Image

on:
  push:
    branches:
      - custom-docker-image
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker/custom-fuzzy-search/**'
      - '.github/workflows/docker-fuzzy-search.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/custom-fuzzy-search/Dockerfile
          push: true
          tags: |
            danielrosehill/homebox:fuzzy-search
            danielrosehill/homebox:latest
          cache-from: type=registry,ref=danielrosehill/homebox:buildcache
          cache-to: type=registry,ref=danielrosehill/homebox:buildcache,mode=max
